image: python:3.13-slim

stages:
  - checks

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "api"'

checks:
  stage: checks
  before_script:
    - pip install --no-cache-dir uv
    - uv sync --frozen
  script:
    - uv run ruff format --check .
    - uv run ruff check src tests
    - uv run mypy src tests
    - uv run pytest
